### ISSUE TITLE
Unescape HTML characters

### ISSUE THREAD

**Issue by r7kamura** [r7kamura/retro-twitter-client#3]
![image](https://cloud.githubusercontent.com/assets/111689/9530363/3eceee90-4d3a-11e5-81f3-b18fb77a7d46.png)

**Comment by rhysd** [comment]
b3a4cb81d6a41be8a97596fe188acbde28dcb87d should fix this issue.

**Comment by r7kamura** [comment]
:tada:

**Comment by r7kamura** [comment]
![image](https://cloud.githubusercontent.com/assets/111689/9567828/7792d8d2-4f73-11e5-92a3-c51527f14c36.png)

:weary:

**Comment by rhysd** [comment]
:bulb: https://github.com/twitter/twitter-text/tree/master/js#npm-users

**Comment by r7kamura** [comment]
It looks like double-escaped in TweetBody component, so we need to remove one of them...
